name: PaperTest
version: ${project.version}
main: com.pricejoshua.papertest.PaperTest
api-version: 1.16
commands:
  stats:
    description: Displays the amount of blocks placed
  enter_contest:
    description: Enters the block placing contest
  reset_blocks:
    description: Reset the contest
  save:
    description: hello